name: Generate Snake Animation

on:
  schedule:
    # run automatically every 12 hours
    - cron: "0 */12 * * *"
  
  workflow_dispatch:
  
  push:
    branches:
    - main
    - master
    
jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/github-contribution-grid-snake.svg
            assets/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#FF003C&color_dots=#0D1117,#003344,#006688,#0099CC,#00F0FF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Hide summary bar
        run: |
          sed -i 's/<rect class="u[^>]*>//g' assets/github-contribution-grid-snake.svg
          sed -i 's/<rect class="u[^>]*>//g' assets/github-contribution-grid-snake-dark.svg
          sed -i 's/height="192"/height="150"/g' assets/github-contribution-grid-snake.svg
          sed -i 's/height="192"/height="150"/g' assets/github-contribution-grid-snake-dark.svg
          sed -i 's/880 192/880 150/g' assets/github-contribution-grid-snake.svg
          sed -i 's/880 192/880 150/g' assets/github-contribution-grid-snake-dark.svg
          
      - name: Push github-contribution-grid-snake.svg to the main branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update snake animation"
          file_pattern: 'assets/*.svg'
